### ISSUE TITLE
REST Reference is missing list of rate limit buckets

### ISSUE THREAD

**Issue by NightmareJoker2** [mixer/developer-docs#10]
The REST API reference documentation used to include information about the rate limits and the relevant rate limit buckets. This information is now missing. Please re-add it.

Yes, I am aware the information is hidden somewhere in the guides at https://dev.mixer.com/guides/core/ratelimits but this is neither immediately obvious nor easily discoverable.

**Comment by ProbablePrime** [comment]
We're deprecating this area eventually, so I will add a link to the new area's rate limit guide to get us a cross link in place.
