### ISSUE TITLE
interactive-node API reference seems to be missing

### ISSUE THREAD

**Issue by gostay** [mixer/developer-docs#14]
From https://dev.mixer.com/guides/mixplay/introduction I follow a link to https://mixer.github.io/interactive-node/ hoping to find API reference, but the content in the panel on the right seems not to have been generated.  I see only setWebSocket, and no other functions.

On this same page ( https://mixer.github.io/interactive-node/ ) there's a specific reference to the "Client.open" method that links to https://mixer.github.io/interactive-node/classes/client.html#open which returns a 404, which I assume is the same issue.

**Comment by ProbablePrime** [comment]
Thanks!, i opened: https://github.com/mixer/interactive-node/issues/108 on the client awhile back to track there too.
