### ISSUE TITLE
How to check if user has followed

### ISSUE THREAD

**Issue by iDiffusion** [mixer/developer-docs#19]
Im having difficulties checking if a user has followed the desired channel, everytime that i run 'get' for '/channels/channelid/follow' i get a shortened list of the users that follow, how would i get the full list of just check if the user is following?

**Comment by iDiffusion** [comment]
Is there an easier way to check if a user has followed?

**Comment by n0em** [comment]
The `/users/{user}/follows` endpoint is the easiest way to check if a user has followed a channel, without monitoring that action in real time using Constellation.

The endpoint supports query parameters, so if you are only looking for whether a user is following a certain channel, you could do the following:

`/users/{PossibleFollowerUserID}/follows?where=token:eq:{ChannelToken}`

If the response contains an empty array, you know they aren't following that channel.
