### ISSUE TITLE
Constellation Live Subscribe Refference errors

### ISSUE THREAD

**Issue by magnus97** [mixer/developer-docs#31]
In the Live Subscribe method page there is pointers that is pointed to #events_live_events and #introduction__liveloading_limits but it dosent exists and displays it as regular text on the page
![chrome_2019-01-23_06-32-59](https://user-images.githubusercontent.com/4028289/51585290-1759ac00-1ed9-11e9-847f-f8f9943de63d.png)

**Comment by n0em** [comment]
Thanks for the report! I've fixed this in https://github.com/mixer/developer-docs/commit/96e7bb84081b942b1ea671d1a2f1a2a782b30969. Please do let us know if you notice any other issues :)

Have a good one!
