### ISSUE TITLE
UserUpdate incorrect response

### ISSUE THREAD

**Issue by NickParks** [mixer/developer-docs#39]
The [UserUpdate](https://dev.mixer.com/reference/chat/events/userupdate) chat event states that a `permissions` and `username` are passed when called.

After being unauthenticated and authenticated with the chat socket, neither are passed upon any role update. 

[Image here](https://cdn.discordapp.com/attachments/294231340667371521/580139126616096768/Screen_Shot_2019-05-20_at_2.04.56_PM.png)

Also mentioned in the community devs channel in the community discord.

**Comment by ProbablePrime** [comment]
These properties are no longer sent so they have been removed from the documentation
