### ISSUE TITLE
Revert Needed: Java Chatbot Auth

### ISSUE THREAD

**Issue by n0em** [mixer/developer-docs#40]
Auth-related changes from https://github.com/mixer/developer-docs/commit/fa76b0848ea332b7ac6250373353d59d03c3877f to `pages/01.guides/02.chat/02.ChatBot/doc.md` needs to be reverted.

Lines 326 and 400 should go back to `MixerAPI mixer = new MixerAPI("Click here to get your Client ID!", "Click here to get your Token!");`

...oopsie...

**Comment by ProbablePrime** [comment]
Thanks, feel free to PR this. Its a simple enough change to go through.

**Comment by n0em** [comment]
There was some discussion on the community discord, and it sounds like there are some differences in the argument order between the GitHub version and what's on Maven. So depending on where you pull from, it either will work as doc'd or won't.

**Comment by ProbablePrime** [comment]
The new maven stuff -> Github maven means this change was needed its now done. I'm still confused but they both matchh now.
