### ISSUE TITLE
Constellation endpoint is nowhere to be found

### ISSUE THREAD

**Issue by ooojustin** [mixer/developer-docs#43]
For some reason the actual URI to the Constellation websocket is mentioned nowhere? I was able to find it by snooping around the [beam-client-java source](https://github.com/mixer/beam-client-java/blob/274810dddebdc759b70176ecf4ecdf2e17f0a1a4/src/main/java/com/mixer/api/resource/constellation/ws/MixerConstellationConnection.java#L21) but it should probably be on the actual [landing page](https://github.com/mixer/developer-docs/blob/master/pages/02.reference/02.constellation/landing.md).

**Comment by ProbablePrime** [comment]
You're absolutely, right. I'll get this sorted.

**Comment by ProbablePrime** [comment]
Ok this is resolved in: https://github.com/mixer/developer-docs/commit/bc07a3475224a127d300a93cb5cd29771021f824

thanks
