### ISSUE TITLE
Live Indicator/view count overlays other UI elements

### ISSUE THREAD

**Issue by AtomicCorpse** [mixer/developer-docs#47]
Just noticed this while having a look at the site.
![Screenshot_20190812-114055](https://user-images.githubusercontent.com/12871503/62859903-7e647400-bcf6-11e9-9076-9c9a7609416f.jpg)
The live Indicator and the current viewer count indicators seem to overlap other various UI elements like the menu

**Comment by ProbablePrime** [comment]
Hey @AtomicCorpse this issue tracker is for bugs relating to https://dev.mixer.com for our main site you're better of using our contact page at https://mixer.com/contact
