### ISSUE TITLE
creating a chatbot i have a issue

### ISSUE THREAD

**Issue by SweptAaron** [mixer/developer-docs#48]
in java i try to compile my chatbot, but when i try tu execute netbeans throw the net message
Exception in thread "main" java.util.concurrent.ExecutionException: com.mixer.api.http.HttpBadResponseException

some help please?

**Comment by ProbablePrime** [comment]
This means that our API is responding with a bad status code, could you attach a debugger and take a look at the properties of the thrown exception?

Thank you

**Comment by zlavallee** [comment]
I have the same issue. The error message is:

`
HTTP/1.1 401 Unauthorized:
{"errorCode":24325,"errorMessage":"OAuth token is invalid"}
`

**Comment by zlavallee** [comment]
I see the issue. The token and the client ID are mixed up in the documentation here:
`MixerAPI mixer = new MixerAPI("Click here to get your Token!", "Click here to get your Client ID!");
to get your Client ID!");`

 Just swap them and they work. Please update the docs thanks.

**Comment by ProbablePrime** [comment]
I have resolved the doc issue thank you
