### ISSUE TITLE
Easy Start up guide

### ISSUE THREAD

**Issue by Muddster89** [mixer/developer-docs#50]
So i notice you jump right into dev. So for those of us that have never done development and come to the channel might find it hard to learn to start. 

I have a comp sci degree in programming but its been a while since I have coded. So trying to follow along with what programs you have running, what IDE's are being used or even what github is might be off putting for people that want to create interactive options on their panels.

So a suggestion is a "Get started video" Where you walk through what programs should be downloaded, which programs are being used for what purposes etc. Possibly even toss up the boiler plate code that you have shown in most of your dev channel to allow people to get that and just drop it on their stream and be able to edit a barebones ability. I find that once someone has a small piece of code that works but then can be edited to then suite their needs they are more likely to go looking for new and improved ways to do things. 

Where as if they do not even know where to start will sometimes get discouraged and not even try.

Thanks
Flyingsquirrel89/Muddster89

**Comment by ProbablePrime** [comment]
Hey @Muddster89 have you checked out tutorials? https://dev.mixer.com/guides/chat/chatbot

is an example, provides everything you need in a document to follow. Including full code.
