### ISSUE TITLE
Invalid OAuth scopes for various /channels REST endpoints

### ISSUE THREAD

**Issue by Celeo** [mixer/developer-docs#55]
On the [/channels endpoint listing](https://dev.mixer.com/rest/index.html#channels), several endpoints list the `channel:update` scope as required. Per the [list of OAuth scopes](https://dev.mixer.com/reference/oauth/scopes) (and my attempts to get the scope listed in the REST endpoint list), this scope does not exist.

I would make the doc changes myself, but it looks like the "Rest Reference" is being loaded from somewhere else, per [this doc page](https://github.com/mixer/developer-docs/blob/master/pages/02.reference/06.rest/doc.md).

**Comment by Celeo** [comment]
A similar issue exists with the /notification endpoints - the docs state that the "user:notification" scope is required, but that scope does not exist. A similarly-named scope "user:notification:self" exists.

**Comment by ProbablePrime** [comment]
Thanks for your report, ive resolved those.
