### ISSUE TITLE
reccomend typo in two places in this repository

### ISSUE THREAD

**Issue by TyrenDe** [mixer/developer-docs#58]
reccomend is spelled wrong. It should be "recommend"

Places:
pages/02.reference/01.chat/05.ChatChattersList/doc.md
CONTRIBUTING.md

**Comment by ProbablePrime** [comment]
Fixed in: https://github.com/mixer/developer-docs/commit/73ab7ecbbeee2b0270b8c476b3432f1ab01c47d3

thank you
