### ISSUE TITLE
$04 Console Errors reg

### ISSUE THREAD

**Issue by Archana-Vijayakumar** [mixer/developer-docs#61]
While using the mixer live stream URL in my site and I'm facing few console errors from mixer API
When I go to the URL https://mixer.com/browse/games/568925/call-of-duty-modern-warfare
This issue not only to call of duty game almost all the games.

<img width="459" alt="errors" src="https://user-images.githubusercontent.com/30137443/70793064-83c6ed80-1dc0-11ea-8531-6c0e1490648d.PNG">

**Comment by ProbablePrime** [comment]
Hey Archana, 

You've reached our developer site issue tracker which is not for support of the main mixer.com website. For that please open a support ticket at https://mixer.com/contact.

Thanks!
