### ISSUE TITLE
Live Events docs unclear about partial data

### ISSUE THREAD

**Issue by SReject** [mixer/developer-docs#62]
Through out the docs the following appears

> Please note this event may not necessarily include the entire [...] resource.

While on the surface this may seem adequate it should be clarified that only properties that have changed for the resource will be returned, even in cases where the model is nested; indicating a deep merge is required for a cached model

Further more for properties of a model that are an array/list, it should be noted that the array should replace the cached model's value for the property

An example of this is `user:id:update`, assuming `user.social.verified` updates, mixer will only return that change and not the full SocialInfo model:

```js
{ social: { verified: [ /* ... */ ] } }
```

**Comment by ProbablePrime** [comment]
Ok i've created some brand new documentation here to help. 

Its linked to from each of the update events which are affected by this it should suffice but feel free to comment if you'd like further clarification.
