### ISSUE TITLE
How can I have multiple sockets?

### ISSUE THREAD

**Issue by kpetrone-accela** [mixer/developer-docs#70]
I am trying to develop a chat bot for my community. I followed along with the tutorial in node.js on the website, but am unable to get a collection of the sockets that are connected to multiple channels. Is there any way that I can do that?

**Comment by ProbablePrime** [comment]
Absolutely, That's largely up to you though. 

You'll need to create more instances of `Mixer.Socket` and set them up with appropriate connection details.

**Comment by kpetrone-accela** [comment]
I just now saw this, but that is basically how I figured it out. Thank you for the response!
