### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by undeference** [mixer/developer-docs#72]
<https://mixerdev2.azurewebsites.net/guides/core/liveupdatesguides/reference/constellation/introduction> should be <https://mixerdev2.azurewebsites.net/reference/constellation/introduction> linked from <https://mixerdev2.azurewebsites.net/guides/core/liveupdatesguides>

**Comment by undeference** [comment]
There are also broken links on <https://mixerdev2.azurewebsites.net/reference/constellation/introduction>

**Comment by ProbablePrime** [comment]
Thank you, we're having some routing issues i'm working on.

**Comment by ProbablePrime** [comment]
These should be fixed, thank you for the help
