### ISSUE TITLE
New design's `notice` design element has poor readability

### ISSUE THREAD

**Issue by NightmareJoker2** [mixer/developer-docs#9]
The `notice` design block is yellow with white text. This offers poor contrast.

Example: https://dev.mixer.com/reference/oauth#using-oauth

The text in these boxes (and especially in the case of the example) is often very important and should be easy to read and follow, especially by novice developers.

Suggested solution: Use a much darker background color instead of yellow, or a dark text color.

**Comment by ProbablePrime** [comment]
You're right thanks for catching this. It fails to meet contrast ratios. We'll address this: ![](https://i.probableprime.co.uk/181004-K7USmRTrFtpw4ucdU3jQ.png)

**Comment by ProbablePrime** [comment]
We fixed this awhile ago. The new notices look a tad ugly but I will ask design to do another pass when they get the chance.
